name: impakdio
description: "An Api Package base on dio"
version: 1.0.0
homepage: https://github.com/impaktek/impakdio

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  http: ^1.2.2
  pretty_dio_logger: ^1.4.0
  mockito: ^5.0.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
